// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ProjectCreate = `-- name: ProjectCreate :exec
INSERT INTO pg_storage.kanban.project (id, name, description)
VALUES ($1, $2, $3)
`

type ProjectCreateParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        *string     `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
}

func (q *Queries) ProjectCreate(ctx context.Context, arg ProjectCreateParams) error {
	_, err := q.db.Exec(ctx, ProjectCreate, arg.ID, arg.Name, arg.Description)
	return err
}
